// AUTOGENERATED FILE: DO NOT EDIT (idlc v0.2.3)
#pragma once

#include <stdint.h>
#include "object.h"

typedef Object IAppController;
#define IAppController_CBO_INTERFACE_WAIT UINT32_C(1)

#define IAppController_ERROR_APP_SUSPENDED INT32_C(10)
#define IAppController_ERROR_APP_BLOCKED_ON_LISTENER INT32_C(11)
#define IAppController_ERROR_APP_UNLOADED INT32_C(12)
#define IAppController_ERROR_APP_IN_USE INT32_C(13)
#define IAppController_ERROR_NOT_SUPPORTED INT32_C(14)
#define IAppController_ERROR_CBO_UNKNOWN INT32_C(15)
#define IAppController_ERROR_APP_UNLOAD_NOT_ALLOWED INT32_C(16)
#define IAppController_ERROR_APP_DISCONNECTED INT32_C(17)
#define IAppController_ERROR_USER_DISCONNECT_REJECTED INT32_C(18)
#define IAppController_ERROR_STILL_RUNNING INT32_C(19)
#define IAppController_ERROR_APP_RESTART_FAILED INT32_C(20)

#define IAppController_OP_openSession 0
#define IAppController_OP_unload 1
#define IAppController_OP_getAppObject 2
#define IAppController_OP_installCBO 3
#define IAppController_OP_disconnect 4
#define IAppController_OP_restart 5

static inline int32_t
IAppController_release(Object self)
{
    return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IAppController_retain(Object self)
{
    return Object_invoke(self, Object_OP_retain, 0, 0);
}

/*
*
*  Opens a session with the trusted application.
*
*  This method is part of the GP interface for the TA, and should not be directly used (internal to GP framework)
*
*  The caller/implementer (depending on parameter type) manually marshals the
*  content of four input/output buffers.
*
*  @param[in]  cancelCode         Optional code to use for cancellations.
*  @param[in]  connectionMethod   What CA identity credentials to use.
*  @param[in]  connectionData     Optional connection group identifier.
*  @param[in]  paramTypes         Parameter types, 1 byte per parameter.
*  @param[in]  exParamTypes       Extended information for parameters, 1 byte per parameter.
*  @param[in]  i1                 First input buffer.
*  @param[in]  i2                 Second input buffer.
*  @param[in]  i3                 Third input buffer.
*  @param[in]  i4                 Fourth input buffer.
*  @param[out] o1                 First output buffer.
*  @param[out] o2                 Second output buffer.
*  @param[out] o3                 Third output buffer.
*  @param[out] o4                 Fourth output buffer.
*  @param[in]  imem1              First optional memory region.
*  @param[in]  imem2              Second optional memory region.
*  @param[in]  imem3              Third optional memory region.
*  @param[in]  imem4              Fourth optional memory region.
*  @param[out] memrefOutSz1       Desired output size for memref 1, if larger than size provided.
*  @param[out] memrefOutSz2       Desired output size for memref 2, if larger than size provided.
*  @param[out] memrefOutSz3       Desired output size for memref 3, if larger than size provided.
*  @param[out] memrefOutSz4       Desired output size for memref 4, if larger than size provided.
*  @param[out] session            Newly opened session.
*  @param[out] retValue           GP return value.
*  @param[out] retOrigin          Where the GP return value originated.
*
*  @return  Object_OK if successful.
*
*/
static inline int32_t IAppController_openSession(Object self, uint32_t cancelCode_val, uint32_t connectionMethod_val, uint32_t connectionData_val, uint32_t paramTypes_val, uint32_t exParamTypes_val, const void *i1_ptr, size_t i1_len, const void *i2_ptr, size_t i2_len, const void *i3_ptr, size_t i3_len, const void *i4_ptr, size_t i4_len, void *o1_ptr, size_t o1_len, size_t *o1_lenout, void *o2_ptr, size_t o2_len, size_t *o2_lenout, void *o3_ptr, size_t o3_len, size_t *o3_lenout, void *o4_ptr, size_t o4_len, size_t *o4_lenout, Object imem1, Object imem2, Object imem3, Object imem4, uint32_t *memrefOutSz1_ptr, uint32_t *memrefOutSz2_ptr, uint32_t *memrefOutSz3_ptr, uint32_t *memrefOutSz4_ptr, Object *session, uint32_t *retValue_ptr, uint32_t *retOrigin_ptr)
{
    struct bi {
        uint32_t m_cancelCode;
        uint32_t m_connectionMethod;
        uint32_t m_connectionData;
        uint32_t m_paramTypes;
        uint32_t m_exParamTypes;
    } i;

    i.m_cancelCode = cancelCode_val;
    i.m_connectionMethod = connectionMethod_val;
    i.m_connectionData = connectionData_val;
    i.m_paramTypes = paramTypes_val;
    i.m_exParamTypes = exParamTypes_val;
    struct bo {
        uint32_t m_memrefOutSz1;
        uint32_t m_memrefOutSz2;
        uint32_t m_memrefOutSz3;
        uint32_t m_memrefOutSz4;
        uint32_t m_retValue;
        uint32_t m_retOrigin;
    } o = {0,0,0,0,0,0};

    ObjectArg a[] = {
        {.b = (ObjectBuf) { &i, 20 } },
        {.bi = (ObjectBufIn) { i1_ptr, i1_len * sizeof(uint8_t) } },
        {.bi = (ObjectBufIn) { i2_ptr, i2_len * sizeof(uint8_t) } },
        {.bi = (ObjectBufIn) { i3_ptr, i3_len * sizeof(uint8_t) } },
        {.bi = (ObjectBufIn) { i4_ptr, i4_len * sizeof(uint8_t) } },
        {.b = (ObjectBuf) {  &o, 24 } },
        {.b = (ObjectBuf) { o1_ptr, o1_len * sizeof(uint8_t) } },
        {.b = (ObjectBuf) { o2_ptr, o2_len * sizeof(uint8_t) } },
        {.b = (ObjectBuf) { o3_ptr, o3_len * sizeof(uint8_t) } },
        {.b = (ObjectBuf) { o4_ptr, o4_len * sizeof(uint8_t) } },
        {.o = imem1 },
        {.o = imem2 },
        {.o = imem3 },
        {.o = imem4 },
        {.o = Object_NULL },
    };

    int32_t result = Object_invoke(self, IAppController_OP_openSession, a, ObjectCounts_pack(5, 5, 4, 1));

    *memrefOutSz1_ptr = o.m_memrefOutSz1;
    *memrefOutSz2_ptr = o.m_memrefOutSz2;
    *memrefOutSz3_ptr = o.m_memrefOutSz3;
    *memrefOutSz4_ptr = o.m_memrefOutSz4;
    *retValue_ptr = o.m_retValue;
    *retOrigin_ptr = o.m_retOrigin;
    *o1_lenout = a[6].b.size / sizeof(uint8_t);
    *o2_lenout = a[7].b.size / sizeof(uint8_t);
    *o3_lenout = a[8].b.size / sizeof(uint8_t);
    *o4_lenout = a[9].b.size / sizeof(uint8_t);
    *session = a[14].o;
    return result;
}

/*
*
*  Unloads the trusted application.
*
*  This function fails if the application is currently busy. The caller is
*  expected to try again at a later time.
*
*  @return  Object_OK if successful.
*
*/
static inline int32_t IAppController_unload(Object self)
{
    return Object_invoke(self, IAppController_OP_unload, 0, 0);
}

/*
*
*  Gets the object implementing app-provided functionalities.
*
*  @param[out] obj          Returned object.
*
*  @return  Object_OK on success.
*
*/
static inline int32_t IAppController_getAppObject(Object self, Object *obj)
{
    ObjectArg a[] = {
        {.o = Object_NULL },
    };

    int32_t result = Object_invoke(self, IAppController_OP_getAppObject, a, ObjectCounts_pack(0, 0, 0, 1));

    *obj = a[0].o;
    return result;
}

/*
*
*  Installs a CallBack Object provided by the client.
*
*  @param[in] uid           UID of service class to register.
*  @param[in] obj           Object implementing the interface.
*
*  @return  Object_OK on success.
*
*/
static inline int32_t IAppController_installCBO(Object self, uint32_t uid_val, Object obj)
{
    ObjectArg a[] = {
        {.b = (ObjectBuf) { &uid_val, sizeof(uint32_t) } },
        {.o = obj },
    };

    int32_t result = Object_invoke(self, IAppController_OP_installCBO, a, ObjectCounts_pack(1, 0, 1, 0));

    return result;
}

/*
*
*  Disconnect client from the trusted application.
*
*  This method removes the client connection to the app while leaving the app
*  loaded. After a successful disconnect, the only methods allowed on the
*  IAppController object are retain and release. After a successful disconnect,
*  a new IAppController object can be obtained for the app by calling
*  IAppLoader_connect.
*
*  Fails if the trusted application rejects the disconnect request.
*
*  @return  Object_OK if successful.
*
*/
static inline int32_t IAppController_disconnect(Object self)
{
    return Object_invoke(self, IAppController_OP_disconnect, 0, 0);
}

/*
*
*  Restart the TA.
*  Only a TA that has not been unloaded can be restarted.
*  @return  Object_OK if successful.
* *
*/
static inline int32_t IAppController_restart(Object self)
{
    return Object_invoke(self, IAppController_OP_restart, 0, 0);
}

