// AUTOGENERATED FILE: DO NOT EDIT (idlc v0.2.3)
#pragma once

#include <stdint.h>
#include "object.h"
#include "IIO.h"
#include "ICredentials.h"

typedef Object IClientEnv;

#define IClientEnv_ERROR_COMMONLIBS_ALREADY_LOADED INT32_C(10)
#define IClientEnv_ERROR_APP_REGION_ALREADY_SET INT32_C(11)

#define IClientEnv_OP_open 0
#define IClientEnv_OP_registerLegacy 1
#define IClientEnv_OP_registerAsClient 2
#define IClientEnv_OP_registerWithWhitelist 3
#define IClientEnv_OP_notifyDomainChange 4
#define IClientEnv_OP_registerWithCredentials 5
#define IClientEnv_OP_loadCmnlibFromBuffer 6
#define IClientEnv_OP_configTaRegion 7
#define IClientEnv_OP_adciAccept 8
#define IClientEnv_OP_adciShutdown 9

static inline int32_t
IClientEnv_release(Object self)
{
    return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IClientEnv_retain(Object self)
{
    return Object_invoke(self, Object_OP_retain, 0, 0);
}

/*
*
*   Gets a service object from the Client Environment.
*
*   @param[in]  uid  Identifies a class of service object.
*   @param[out] obj  Instance of the requested service.
*
*   @return
*   Object_OK on success.
*
*/
static inline int32_t IClientEnv_open(Object self, uint32_t uid_val, Object *obj)
{
    ObjectArg a[] = {
        {.b = (ObjectBuf) { &uid_val, sizeof(uint32_t) } },
        {.o = Object_NULL },
    };

    int32_t result = Object_invoke(self, IClientEnv_OP_open, a, ObjectCounts_pack(1, 0, 0, 1));

    *obj = a[1].o;
    return result;
}

/*
*
*   Registers a REE client with the specified credentials and returns a
*   client environment object that the client can use to obtain service
*   objects. \n
*
*   @note1hang: This method is DEPRECATED.
*
*   @param[in] credentials  Buffer containing credentials identifying the
*                           client.
*   @param[out] clientEnv   Returned registered client environment object.
*
*   @return
*   Object_OK on success.
*
*/
static inline int32_t IClientEnv_registerLegacy(Object self, const void *credentials_ptr, size_t credentials_len, Object *clientEnv)
{
    ObjectArg a[] = {
        {.bi = (ObjectBufIn) { credentials_ptr, credentials_len * sizeof(uint8_t) } },
        {.o = Object_NULL },
    };

    int32_t result = Object_invoke(self, IClientEnv_OP_registerLegacy, a, ObjectCounts_pack(1, 0, 0, 1));

    *clientEnv = a[1].o;
    return result;
}

/*
*
*   Registers a REE client with the specified credentials and returns a
*   client environment object that the client can use to obtain service
*   objects.
*
*   @param[in] credentials  Callback object implementing the IIO
*                           interface which can be queried to return the REE
*                           credentials of the client being registered.
*   @param[out] clientEnv   Returned registered client environment object.
*
*   @return
*   Object_OK on success.
*
*/
static inline int32_t IClientEnv_registerAsClient(Object self, IIO credentials, Object *clientEnv)
{
    ObjectArg a[] = {
        {.o = credentials },
        {.o = Object_NULL },
    };

    int32_t result = Object_invoke(self, IClientEnv_OP_registerAsClient, a, ObjectCounts_pack(0, 0, 1, 1));

    *clientEnv = a[1].o;
    return result;
}

/*
*
*   Registers a REE client with the specified credentials and restricts it
*   to the specified list of UIDs. The client can use the returned client
*   environment object to obtain service objects.
*
*   The returned client environment object can only obtain the
*   services with UIDs in the passed UID list.
*
*   @param[in] credentials  Callback object implementing the IIO
*                           interface which can be queried to return the REE
*                           credentials of the client being registered.
*   @param[in] uids         Class UIDs list the returned client environment
*                           object can obtain.
*   @param[out] clientEnv   Returned registered client environment object.
*
*   @return
*   Object_OK on success.
*
*/
static inline int32_t IClientEnv_registerWithWhitelist(Object self, IIO credentials, const uint32_t *uids_ptr, size_t uids_len, Object *clientEnv)
{
    ObjectArg a[] = {
        {.bi = (ObjectBufIn) { uids_ptr, uids_len * sizeof(uint32_t) } },
        {.o = credentials },
        {.o = Object_NULL },
    };

    int32_t result = Object_invoke(self, IClientEnv_OP_registerWithWhitelist, a, ObjectCounts_pack(1, 0, 1, 1));

    *clientEnv = a[2].o;
    return result;
}

/*
*
*  Asserts that QTEE has no references to remote NS domain objects other than
*  the single reference to the primordial object and that the NS domain has no
*  references to QTEE objects other than the single reference to the root
*  ClientEnv.
*
*  @return Object_OK on success, else assert on failure.
*
*/
static inline int32_t IClientEnv_notifyDomainChange(Object self)
{
    return Object_invoke(self, IClientEnv_OP_notifyDomainChange, 0, 0);
}

/*
*
*   Registers a REE client with the ICredentials object and returns a
*   client environment object that the client can use to obtain service
*   objects.
*
*   @param[in] credentials  Callback object implementing the ICredentials
*                           interface which can be queried to return the REE
*                           credentials of the client being registered.
*                           This can be NULL only if client code is privilieged
*                           code (kernel or higher exception level.)
*   @param[out] clientEnv   Returned registered client environment object.
*
*   @return
*   Object_OK on success.
*
*/
static inline int32_t IClientEnv_registerWithCredentials(Object self, ICredentials credentials, Object *clientEnv)
{
    ObjectArg a[] = {
        {.o = credentials },
        {.o = Object_NULL },
    };

    int32_t result = Object_invoke(self, IClientEnv_OP_registerWithCredentials, a, ObjectCounts_pack(0, 0, 1, 1));

    *clientEnv = a[1].o;
    return result;
}

/*
*
*  Loads Cmnlib binary.
*  The library binary is passed as a buffer.
*
*  @param[in]  cmnlibElf         Buffer containing ELF image.
*
*  @return  Object_OK if successful.
*
*/
static inline int32_t IClientEnv_loadCmnlibFromBuffer(Object self, const void *cmnlibElf_ptr, size_t cmnlibElf_len)
{
    ObjectArg a[] = {
        {.bi = (ObjectBufIn) { cmnlibElf_ptr, cmnlibElf_len * sizeof(uint8_t) } },
    };

    int32_t result = Object_invoke(self, IClientEnv_OP_loadCmnlibFromBuffer, a, ObjectCounts_pack(1, 0, 0, 0));

    return result;
}

/*
*
*  Configure TA region.
*  TA region address and length is passed as a buffer.
*
*  @param[in]  appRgnAddr         TA region base address.
*  @param[in]  appRgnSize         TA region size.
*
*  @return  Object_OK if successful.
*
*/
static inline int32_t IClientEnv_configTaRegion(Object self, uint64_t appRgnAddr_val, uint32_t appRgnSize_val)
{
    struct bi {
        uint64_t m_appRgnAddr;
        uint32_t m_appRgnSize;
    } i;

    i.m_appRgnAddr = appRgnAddr_val;
    i.m_appRgnSize = appRgnSize_val;
    ObjectArg a[] = {
        {.b = (ObjectBuf) { &i, 12 } },
    };

    int32_t result = Object_invoke(self, IClientEnv_OP_configTaRegion, a, ObjectCounts_pack(1, 0, 0, 0));

    return result;
}

/*
*
*  Registers a thread to be used for ADCI (Arbitrary Destination Callback
*  Invocations). Will not return until successfully canceled unless an error
*  occurs.
*
*  @return
*  Object_OK on successful cancel of ADCI accept thread.
*  Object_ERROR on failure.
*
*/
static inline int32_t IClientEnv_adciAccept(Object self)
{
    return Object_invoke(self, IClientEnv_OP_adciAccept, 0, 0);
}

/*
*
*  Cancels any previously registered ADCI accept thread.
*
*  @return
*  Object_OK on success.
*  Object_ERROR on failure.
*
*/
static inline int32_t IClientEnv_adciShutdown(Object self)
{
    return Object_invoke(self, IClientEnv_OP_adciShutdown, 0, 0);
}

