// AUTOGENERATED FILE: DO NOT EDIT (idlc v0.2.3)
#pragma once

#include <stdint.h>
#include "object.h"

typedef Object IQSEEComCompat;

#define IQSEEComCompat_ERROR_APP_UNAVAILABLE INT32_C(10)

#define IQSEEComCompat_OP_sendRequest 0
#define IQSEEComCompat_OP_disconnect 1
#define IQSEEComCompat_OP_unload 2

static inline int32_t
IQSEEComCompat_release(Object self)
{
    return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IQSEEComCompat_retain(Object self)
{
    return Object_invoke(self, Object_OP_retain, 0, 0);
}


static inline int32_t IQSEEComCompat_sendRequest(Object self, const void *reqIn_ptr, size_t reqIn_len, const void *rspIn_ptr, size_t rspIn_len, void *reqOut_ptr, size_t reqOut_len, size_t *reqOut_lenout, void *rspOut_ptr, size_t rspOut_len, size_t *rspOut_lenout, const uint32_t *embeddedBufOffsets_ptr, size_t embeddedBufOffsets_len, uint32_t is64_val, Object smo1, Object smo2, Object smo3, Object smo4)
{
    ObjectArg a[] = {
        {.bi = (ObjectBufIn) { reqIn_ptr, reqIn_len * sizeof(uint8_t) } },
        {.bi = (ObjectBufIn) { rspIn_ptr, rspIn_len * sizeof(uint8_t) } },
        {.bi = (ObjectBufIn) { embeddedBufOffsets_ptr, embeddedBufOffsets_len * sizeof(uint32_t) } },
        {.b = (ObjectBuf) { &is64_val, sizeof(uint32_t) } },
        {.b = (ObjectBuf) { reqOut_ptr, reqOut_len * sizeof(uint8_t) } },
        {.b = (ObjectBuf) { rspOut_ptr, rspOut_len * sizeof(uint8_t) } },
        {.o = smo1 },
        {.o = smo2 },
        {.o = smo3 },
        {.o = smo4 },
    };

    int32_t result = Object_invoke(self, IQSEEComCompat_OP_sendRequest, a, ObjectCounts_pack(4, 2, 4, 0));

    *reqOut_lenout = a[4].b.size / sizeof(uint8_t);
    *rspOut_lenout = a[5].b.size / sizeof(uint8_t);
    return result;
}


static inline int32_t IQSEEComCompat_disconnect(Object self)
{
    return Object_invoke(self, IQSEEComCompat_OP_disconnect, 0, 0);
}


static inline int32_t IQSEEComCompat_unload(Object self)
{
    return Object_invoke(self, IQSEEComCompat_OP_unload, 0, 0);
}

